SiteUserBundle_login:
    pattern:  /login
    defaults: { _controller: SiteUserBundle:User:login }
    
SiteUserBundle_logout:
    pattern:  /logout
    defaults: { _controller: SiteUserBundle:User:logout }
    
SiteUserBundle_logincheck:
    pattern:  /login_check
    defaults: { _controller: SiteUserBundle:User:securityCheck }
    requirements:
        _method:  POST

SiteUserBundle_locale:
    pattern:  /locale/{_locale}
    defaults: { _controller: SiteUserBundle:User:setLocale }
    
SiteUserBundle_password_recovery:
    pattern:  /password_recovery
    defaults: { _controller: SiteUserBundle:User:passwordRecovery }

SiteUserBundle_password_recovery_do:
    pattern:  /password_recovery/{email}/{hash}
    defaults: { _controller: SiteUserBundle:User:passwordRecoveryDo }
    
    
SiteUserBundle_new:
    pattern:  /new
    defaults: { _controller: SiteUserBundle:User:new }

SiteUserBundle_create:
    pattern:  /create
    defaults: { _controller: SiteUserBundle:User:create }
    requirements:
        _method:  POST
        
SiteUserBundle_index:
    pattern:  /
    defaults: { _controller: SiteUserBundle:User:index }
    
SiteUserBundle_password:
    pattern:  /password
    defaults: { _controller: SiteUserBundle:User:password }

SiteUserBundle_changepassword:
    pattern:  /changepassword
    defaults: { _controller: SiteUserBundle:User:changePassword }
    requirements:
        _method:  POST