<?php

namespace Core\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function createUser(User $user, $addresses = array())
    {
        if($user)
        {
            $em =  $this->getEntityManager();
            $priceGroup = $em->getRepository('CoreUserBundle:PriceGroup')->findOneBy(array("default" => true));
            if ($priceGroup) {
                $user->setPriceGroup($priceGroup); 
            }
            $user->getAddresses()->clear();
            $em->persist($user);
            $em->flush();
            if(!empty($addresses))
            {
                foreach($addresses as $addr)
                {
                    if(!empty($addr))
                    {
                        $addr->setUser($user);
                        $user->getAddresses()->add($addr);
                        $em->persist($addr);
                    }
                }
                $em->persist($user);
            }
            $em->flush();
        }
        return $user;
    }
}