parameters:
#    core_product.example.class: Core\ProductBundle\Example

services:
#    core_product.example:
#        class: %core_product.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
