<?php

namespace Core\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends EntityRepository
{
    public function getUserAddressQueryBuilder($userId = null)
    {
        $queryBuilder = $this->getEntityManager()->createQueryBuilder()
                    ->select("a")
                    ->from('CoreShopBundle:Address', "a")
                    ->addOrderBy('a.name', 'ASC')
                    ->addOrderBy('a.id', 'ASC');                    
        if($userId !== null)
        {
            $queryBuilder->andWhere("a.user = :uid")
            ->setParameter('uid', $userId);
        }
        return $queryBuilder;
    }
}