<?php

namespace Core\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentRepository extends EntityRepository
{
    public function setHint(\Doctrine\ORM\Query $query)
    {
        return $query->setHint(\Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker');
    }
    
    public function getPaymentQueryBuilder()
    {
        return $queryBuilder = $this->getEntityManager()->createQueryBuilder()
            ->select("p")
            ->from("CoreShopBundle:Payment", "p")
            ->orderBy('p.name', 'ASC');
    }
}