<?php

namespace core\BannerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BannerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerRepository extends EntityRepository
{
    public function getBannersQueryBuilder($categoryId = null)
    {
        $queryBuilder = $this->getEntityManager()->createQueryBuilder()
                ->select("b, m")
                ->from("CoreBannerBundle:Banner", "b")
                ->leftJoin("b.media", "m")
                ->addOrderBy("b.id");
        if($categoryId !== null)
        {
            $queryBuilder->andWhere('b.category = :cid')
                    ->setParameter('cid', $categoryId);
        }
        return $queryBuilder;
    }
    
    public function getBannersQuery($categoryId = null)
    {
        return $this->getBannersQueryBuilder($categoryId)->getQuery();
    }
    
    public function getBanners($categoryId = null)
    {
        return $this->getBannersQuery($categoryId)->getResult();
    }
}