<?php

namespace Core\ProductBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Gedmo\Sortable\Entity\Repository\SortableRepository;

/**
 * ProductOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductOptionRepository extends SortableRepository
{
    public function getOptionsByProductQueryBuilder($productId)
    {
        $queryBuilder = $this->getEntityManager()->createQueryBuilder()
                ->select("po")
                ->from("CoreProductBundle:ProductOption", "po") 
                ->andWhere("po.product = :pid")                
                ->setParameter('pid', $productId)
                ->addOrderBy('po.name')
                ->addOrderBy('po.position');
        return $queryBuilder;
    }
    
    
    public function getOptionsByProductQuery($productId)
    {
         return $this->getOptionsByProductQueryBuilder($productId)->getQuery();
    }
}