SiteShopBundle_cart:
    resource: "@SiteShopBundle/Resources/config/routing/cart.yml"
    prefix:   /cart
    
SiteShopBundle_coupon:
    resource: "@SiteShopBundle/Resources/config/routing/coupon.yml"
    prefix:   /coupon
    
SiteShopBundle_checkout:
    resource: "@SiteShopBundle/Resources/config/routing/checkout.yml"
    prefix:   /checkout

SiteShopBundle_address:
    resource: "@SiteShopBundle/Resources/config/routing/address.yml"
    prefix:   /address
    
SiteShopBundle_order:
    resource: "@SiteShopBundle/Resources/config/routing/order.yml"
    prefix:   /order
