cart:
    pattern:  /
    defaults: { _controller: "SiteShopBundle:Cart:index" }
    
cart_check:
    pattern:  /check
    defaults: { _controller: "SiteShopBundle:Cart:check" }
    requirements: { _method: post }
    
cart_add:
    pattern:  /addItem
    defaults: { _controller: "SiteShopBundle:Cart:addItem" }
    requirements: { _method: post }
    
cart_info:
    pattern:  /info
    defaults: { _controller: "SiteShopBundle:Cart:info" }
    
cart_remove:
    pattern:  /removeItem/{index}
    defaults: { _controller: "SiteShopBundle:Cart:removeItem" }

cart_update:
    pattern:  /updateItem
    defaults: { _controller: "SiteShopBundle:Cart:updateItem" }
    requirements: { _method: post }