checkout:
    pattern:  /
    defaults: { _controller: "SiteShopBundle:Checkout:index", _locale: sk}

checkout_guestaddress:
    pattern:  /guestaddress
    defaults: { _controller: "SiteShopBundle:Checkout:guestAddress", _locale: sk}
    requirements: { _method: post }

checkout_user:
    pattern:  /user
    defaults: { _controller: "SiteShopBundle:Checkout:user", _locale: sk }

checkout_useraddress:
    pattern:  /useraddress
    defaults: { _controller: "SiteShopBundle:Checkout:userAddress", _locale: sk }
    requirements:
        _method: post

checkout_paymentshipping:
    pattern:  /paymentshipping
    defaults: { _controller: "SiteShopBundle:Checkout:paymentShipping", _locale: sk}

checkout_savepaymentshipping:
    pattern:  /savepaymentshipping
    defaults: { _controller: "SiteShopBundle:Checkout:savePaymentShipping", _locale: sk }
    requirements:
        _method: post

checkout_confirm:
    pattern:  /confirm
    defaults: { _controller: "SiteShopBundle:Checkout:confirm", _locale: sk }

checkout_order:
    pattern:  /order
    defaults: { _controller: "SiteShopBundle:Checkout:order", _locale: sk }
