<?php

namespace Core\UserTextBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserTextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTextRepository extends EntityRepository
{
    public function getUserText($name, $create = false)
    {
        $entity = $this->findOneByName($name);
        if($entity === null && $create)
        {
             $entity  = new UserText();
             $entity->setName($name);
             $this->getEntityManager()->persist($entity);
             $this->getEntityManager()->flush();
        }
        return $entity;
    }
}
