<?php

namespace Core\CategoryBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr;
use Gedmo\Tree\Entity\Repository\NestedTreeRepository;
/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends NestedTreeRepository
{
    public function getCategoriesByMenu($menu, $parent = null, $onlyenabled = false)
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
               ->select("c")
               ->from("CoreCategoryBundle:Category", "c")
               ->set("c.home", ":home")
               ->andWhere("c.menu = :menu")
               ->setParameter('menu', $menu);
        if($parent !== null)
        {
           $qb ->andWhere("c.parent = :parent")
               ->setParameter('parent', $parent);
        }
        else
        {
            $qb ->andWhere("c.parent is NULL");
        }
        if($onlyenabled)
        {
            $qb->andWhere("c.enabled=:enabled")
                ->setParameter("enabled", $onlyenabled);
        }
        $qb->addOrderBy("c.lft");
        return $qb->getQuery()->getResult();
    }
    
    public function updateHomeCategory($exlude)
    {
       $q = $this->getEntityManager()->createQueryBuilder()
               ->update("CoreCategoryBundle:Category", "c")
               ->set("c.home", ":home")
               ->where("c.id <> :id")
               ->setParameter('home', 'false')
               ->setParameter('id', $exlude)
               ->getQuery();
       $numUpdated = $q->execute(); 
       return $numUpdated;
    }
    
    public function getTreeQueryBuilder($menu = null, $onlyenabled = false, $direct = false, $sortByField = null, $direction = 'ASC')
    {
        $qb = $this->childrenQueryBuilder(null, $direct, $sortByField, $direction);
        if($menu !== null)
        {
            $qb->andWhere("node.menu = :mid")
            ->setParameter('mid', $menu);
        }
        if($onlyenabled)
        {
            $qb->andWhere("node.enabled=:enabled")
                ->setParameter("enabled", $onlyenabled);
        }
        return $qb;
    }
    
    
    public function getTreeQuery($menu = null, $onlyenabled = false, $direct = false, $sortByField = null, $direction = 'ASC')
    {
        $query = $this->getTreeQueryBuilder($menu, $onlyenabled, $direct, $sortByField, $direction)->getQuery();
        //$query = $query->setHint(\Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker');
        return $query;
    }
}